// internal.hpp
// Created by: Jacob Hootman
// Date: June 8, 2020

/*
Copyright 2020 Jacob Hootman. All Rights Reserved.

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#ifndef COM_EXE_PRACTICE_INTERNAL
#define COM_EXE_PRACTICE_INTERNAL 1 // Indicates that the internal header file has been included

#ifdef HACK_OS_WINDOWS
#ifdef COM_EXE_PRACTICE_STATIC
#define COM_EXE_PRACTICE_API
#else
#ifdef COM_EXE_PRACTICE_BUILD
#define COM_EXE_PRACTICE_API __declspec(dllexport)
#else
#define COM_EXE_PRACTICE_API __declspec(dllimport)
#endif // COM_EXE_PRACTICE_BUILD
#endif // COM_EXE_PRACTICE_STATIC
#else
#define COM_EXE_PRACTICE_API	
#endif // HACK_OS_WINDOWS

#endif // !COM_EXE_PRACTICE_INTERNAL